### PR TITLE
Add support for `axios.patch`

### PR DESCRIPTION
**Pull request by ddio**
Found there's no mock for axios.patch : )

### CODE REVIEW

**Comment by patrickocoffeyo** [comment]
@ddio I've just encountered this issue, thanks for the fix! ctk when this is merged and released :)

**Comment by embs** [comment]
Related to #11

**Comment by rileytaylor** [comment]
This is a sticking point for me, we use patch to handle some batch update/create API calls that don't really fit well into the normal rest paradigm. @knee-cola have you had a chance to look at this?

**Comment by cssetian** [comment]
+1 I need to be able to mock the `patch` method as well, was there ever any resolution on this?

**Comment by ikashifullah** [comment]
Hi @knee-cola, if the PR above is fine, could you please merge it so that patch method should solve our problem?

Looking forward to your quick response.

Thank you,

**Comment by knee-cola** [comment]
> Found there's no mock for axios.patch : )

There's little chance I'll be merging any of the pull requests, since I'm no longer using Axios nor this mock.
@ddio would you like to take over this repo?

**Comment by kingjan1999** [comment]
LGTM, thank you!

**Pull request merged**
